#!/usr/bin/env bash

# Usage:
# dep_test evt_name model
# evt_name = event folder name 
# model = velocity model name
# eg: dep_test 20080418093700 cus

eve=$1;
model=$2;

grep -h Event $eve/$model_*.out > junk1.out
grep -h tensor $eve/$model_*.out > junk2.out

depth.pl junk1.out junk2.out $1 > dep_$eve.ps
