#!/usr/bin/env bash

# Usage:
# dep_test evt_name model
# evt_name = event folder name 
# model = velocity model name
# eg: depth_test 20080418093700 cus

eve=$1;
model=$2;

grep -h Event OUTPUT_DIR/*"$eve"*"$model"*.out > OUTPUT_DIR/junk1.out
grep -h tensor OUTPUT_DIR/*"$eve"*"$model"*.out > OUTPUT_DIR/junk2.out

depth.pl OUTPUT_DIR/junk1.out OUTPUT_DIR/junk2.out $1 > OUTPUT_DIR/${eve}_${model}_dep.ps
