#!/bin/bash
# 
# README_EXAMPLE_utu
#
# COMMANDS TO RECREATE INVERSION RESULTS
# Uturuncu event 20100516063454464 
# Velocity model utuhalf
# FMT with lune parameterization
# Full grid search (no line search)
#
# 
# See README_EXAMPLE first -- run the default example.
# 
# 20151110 celso alvizuri - cralvizuri@alaska.edu 
# ==============================================================================


# Part 1. Uturuncu event 20100516063454464, first motion polarity

# 0. Set cap.c to its original condition
cd $CAPHOME
git checkout cap.c 

# 1. Make sure cap is compiled with the following flags, then compile
# NOTE this run should produce the file out.misfit.fmp_
#
# FTC_data=1
# FTC_green=0
# skip_zero_weights=0
# only_first_motion=1
#
# Compile cap
make all

# 3. Run cap
cd $CAPHOME/EXAMPLES
cap.pl -F0.0 -I5/0/5 -J-90/90/-30/30 -Mutuhalf_4/2.4 -E1 -K1 -Y1 -Zw_utuhalf_P01_V10_R01_S10.dat 20100516063454464

# Next compute summary of first motion polarities using the output file
python $CAPHOME/misfit2lune.py out.misfit.fmp_ out.misfit_summary

# 4. Plot polarity misfit on the lune with file out.misfit_summary
# PENDING

# NOTE
# 1. Output file from cap run (step 3) will be file: out.misfit.fmp_
# This file is 708M for grid spacing of 5 degrees and can be deleted after computing summary
# 2. No figure should be created when running first motion polarity (i.e. run cap without -P flag)

# ==============================================================================

