#!/bin/bash
# 
# README_EXAMPLE_utu
#
# COMMANDS TO RECREATE INVERSION RESULTS
# Uturuncu event 20100516063454464 
# Velocity model utuhalf
# FMT with lune parameterization
# Full grid search (no line search)
#
# 
# See README_EXAMPLE first -- run the default example.
# 
# 20151110 celso alvizuri - cralvizuri@alaska.edu 
# ==============================================================================
 

# ==============================================================================
# Part 0. generate Green's functions 
# NOTE "utuhalf" is a homogeneous half-space
# NOTE You do not need to run fk if you have a pre-computed library of Green's functions

# 1. run the frequency-wavenumber code fk
mkdir -p $CAPRUN/models/utuhalf
cd $CAPRUN/models/utuhalf/
cp $CAPHOME/EXAMPLES/20100516063454464/utuhalf .
fk.pl -Mutuhalf/4 -N16384/0.01 11 14 18 19 21 23 31 33 37 50

# 2. run fk again to generate isotropic components
# This will create 3 additional green functions for each distance of the form dist.grn.(a-c),
# eg. 11.grn.a, 11.grn.b, 11.grn.c
fk.pl -Mutuhalf/4 -N16384/0.01 -S0 11 14 18 19 21 23 31 33 37 50

# ==============================================================================
# Part 1. check that cap.c is compiled with the right flags, verify weight files

# 1. go to cap directory and make sure cap is set to its default condition
cd $CAPHOME
git checkout cap.c

# 2. Make sure cap.c is compiled with the following flags, then compile
# NOTE The following examples will run with these set of flags, except for first
# motion polarity example and runs for event 20110622023324299
# FTC_data=1
# FTC_green=0
# skip_zero_weights=0
make cap

# 3. go to run directory
cd $CAPHOME/EXAMPLES

# 4. check values in the w_utuhalf_P01_V10_R01_S10.dat file
# NOTE 
# File name reflects weights for each waveform component, eg: 
#   (PV - PR - SurfV - SurfR - SurfT)  = 10 - 1 - 10 - 10 - 10
# All P arrivals times were obtained from analyst picks
# Surface wave time shifts are set to 0.0 for utuhalf
more 20100516063454464/w_utuhalf_P01_V10_R01_S10.dat

# ==============================================================================
# Part 2. run cap inversion with polarities + body waves + surface waves
# NOTE 
# ISO will be gridded by considering equal spacing in sin(iso) space
# DIP will be gridded by considering equal spacing in cos(dip) space
# All weights should be set as 10 1 10 10 10, which gives higher weights to PV component and surface waves
# All P arrivals times were obtained from analyst picks

# 1. go to the data directory and run cap. 
# NOTE fits for body waves will be scaled by an absolute amplitude, then multiplied by a factor of 3. (this is done with flag "-P3/...")
cd $CAPHOME/EXAMPLES
cap.pl -H0.01 -P3/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -I5/0.1/5 -J-90/90/-30/30 -E1 -K1 -Y1 -Mutuhalf_4/2.4 -Zw_utuhalf_P01_V10_R01_S10.dat 20100516063454464

# 2. compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/20100516063454464_utuhalf_004_P01_V10_R01_S10_fmt_amp_abs.ps &

# 3. Run cap but with all waveform fits normalized within each window. ("relative" scale)
# In cap_plt.plt uncomment line #259 to ensure that relative scaling also applies to surface waves
# $stams = $stamb;

# 4. run cap
cap.pl -H0.01 -P0.5e+0.5/1/30 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -I5/0.1/5 -J-90/90/-30/30 -E1 -K1 -Y1 -Mutuhalf_4/2.4 -Zw_utuhalf_P01_V10_R01_S10.dat 20100516063454464 

# 5. compare results and verify .out file
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/20100516063454464_utuhalf_004_P01_V10_R01_S10_fmt.ps
diff 20100516063454464/utuhalf_004.out 20100516063454464_check/20100516063454464_utuhalf_004_P01_V10_R01_S10.out

# NOTE 
# 1. Flag -P0.5e+0.5/... normalizes seismograms in each window
# 2. Lune grid will NOT do a refined search, so pick -I accordingly (here 5 deg increments on the lune, 0.1 increments in Mw)
# 3. All P arrivals are hand-picked (to within 0.01 s), we set the allowable time shift for P to 0.1 s
# 4. Flag -L gives the half-duration of the synthetics. This is a key command to get high-frequency synthetics in P (but not too high)
# 5. This result is an improvement of the BSSA2014 poster (same event)
# 6. surface wave time shifts are allowed to be between 0.0 s and 4.0 s, which reflects our belief that either:
# (a) the model is systematically too slow
# (b) the depth is wrong
# (c) the origin time is wrong
# 7. We are able to specify the 0.0 to 4.0 s (*) shifts with two changes:
# (1) the relative surface time shifts are +/- 2.0, which is set as -S0.2/2.0/0
# (2) the systematic S_shifts in weight file (last column) are set to 2.0 
# (*) actual time shifts are then 0.0 s (-2.0 + 2.0) and 4.0 s (+2.0 + 2.0)
 
# -----------------------------------------------------------
# Run cap but using different weights for  waveform components
# NOTE Weights are set as 1 1 60 60 60, which gives most weight to surface waves
cap.pl -H0.01 -P0.5e+0.5/1/30 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -I5/0.1/5 -J-90/90/-30/30 -E1 -K1 -Y1 -Mutuhalf_4/2.4 -Zw_utuhalf_P01_V01_R01_S60.dat 20100516063454464 

# 6b. compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_V01_R01_S60.ps &

# -----------------------------------------------------------
# Part 3. Depth test using all waveform components and first motion polarities

# 1. Run cap inversions at each depth
# NOTE this task takes about 30min to complete
for depth in 1 2 3 4 5 6 7 8 9 10; do cap.pl -W1 -Y1 -D1/1/0.5 -H0.01 -C2/10/0.25/0.5 -F0 -L0.1 -S0.05/2.0/0 -P0.5e+0.5/1/30 -T1.5/60 -E1 -K1 -I5/0.1/5 -J-90/90/-30/30 -Mutuhalf_$depth/2.8 -Zw_utuhalf_P01_V10_R01_S10.dat 20100516063454464 ; done

# 2. Plot the result
# NOTE to reproduce figure in the Uturuncu FMT paper open script depth.pl and 
# set flag "$onlydc = 0" to plot beachballs as full moment tensors. Then
# uncomment lines #288, and toggle comments in lines #337 and #338 (see also notes there)
depth_test 20100516063454464 utuhalf

# 3. Compare results
gv dep_20100516063454464.ps &
gv 20100516063454464_check/depth_test_20100516063454464_utuhalf_L_dt.eps &

# -----------------------------------------------------------
# Part 4. run cap inversions WITH and WITHOUT polarities, with body waves. Then with body waves + surface waves.
# NOTE runs without polarities can take hours to complete

# 1a. Run with polarities + body waves + surface waves. Component weights 10-1-10. Plot with absolute amplitudes.
cap.pl -H0.01 -P1e-5/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1/5 -J-90/90/-30/30 -Mutuhalf_4/2.9 -Zw_utuhalf_P01_V10_R01_S10.dat 20100516063454464

# 1b. compare results and verify .out file:
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_P01_V10_R01_S10_scale_abs.ps &
diff 20100516063454464/utuhalf_004.out 20100516063454464_check/utuhalf_004_fmt_P01_V10_R01_S10.out

# 2a. Run WITHOUT polarities, with body waves + surface waves. Component weights 10-1-10
# NOTE this inversion is without polarities, it takes about 3.5hrs to complete
cap.pl -H0.01 -P1e-5/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1/5 -J-90/90/-30/30 -Mutuhalf_4/2.9 -Zw_utuhalf_P00_V10_R01_S10.dat 20100516063454464 

# 2b. Compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_P00_V10_R01_S10.ps

# 3a. Run with polarities + body waves. No surface waves. Component weights 10-1-0
cap.pl -H0.01 -P1e-5/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1/5 -J-90/90/-30/30 -Mutuhalf_4/2.9 -Zw_utuhalf_P01_V10_R01_S00.dat 20100516063454464 

# 3b. Compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_P01_V10_R01_S00.ps

# 4a. Run WITHOUT polarities, with body waves + surface waves. Component weights 10-1-0
# NOTE this inversion is without polarities, it takes about 3.5hrs to complete
cap.pl -H0.01 -P1e-5/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1/5 -J-90/90/-30/30 -Mutuhalf_4/2.9 -Zw_utuhalf_P00_V10_R01_S00.dat 20100516063454464 

# 4b. Compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_P00_V10_R01_S00.ps

# -----------------------------------------------------------
# Part 5. run cap inversions with individual components. All inversions with polarities.
# 1a. Run cap with component PV only
cap.pl -H0.01 -P1e-5/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1/5 -J-90/90/-30/30 -Mutuhalf_4/2.9 -Zw_utuhalf_P01_V10_R00_S00.dat 20100516063454464 

# 1b. Compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_P01_V10_R00_S00.ps

# 2a. Run cap with component PR only
cap.pl -H0.01 -P1e-5/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1/5 -J-90/90/-30/30 -Mutuhalf_4/2.9 -Zw_utuhalf_P01_V00_R01_S00.dat 20100516063454464 

# 2b. Compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_P01_V00_R01_S00.ps

# 3a. Run cap with component Surf only
cap.pl -H0.01 -P1e-5/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1/5 -J-90/90/-30/30 -Mutuhalf_4/2.9 -Zw_utuhalf_P01_V00_R00_S10.dat 20100516063454464 

# 3b. Compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_P01_V00_R00_S10.ps

# -----------------------------------------------------------
# Part 6. run cap inversions with combinations of components. All inversions with polarities.
# 9a. polarities + PV + PR
cap.pl -H0.01 -P0.5e+0.5/1/30 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -I5/0.1/5 -J-90/90/-30/30 -E1 -K1 -Y1 -Mutuhalf_4/2.4 -Zw_utuhalf_P01_V10_R01_S00.dat 20100516063454464

# 9b. compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_V10_R01_S00.ps &

# 10a. polarities + Surface waves
# ************************
# CHECK -- NOTE this inversion is centered around M2.9 M2.9 is the best magnitude for this solution, and also happens to be 
# ************************
# the top limit in grid search (catalog mag = 2.4 +/- 0.5).
cap.pl -H0.01 -P0.5e+0.5/1/30 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -I5/0.1/5 -J-90/90/-30/30 -E1 -K1 -Y1 -Mutuhalf_4/2.9 -Zw_utuhalf_P01_V00_R00_S10.dat 20100516063454464

# 10b. compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_V00_R00_S10.ps &

# 11a. PV + PR + Surf. NO POLARITIES
# NOTE  by not using polarities (to exclude large portions of misfit space), the inversion runs about 3.5 hours
cap.pl -H0.01 -P0.5e+0.5/1/30 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -I5/0.1/5 -J-90/90/-30/30 -E1 -K1 -Y1 -Mutuhalf_4/2.4 -Zw_utuhalf_P00_V10_R01_S10_nopol.dat 20100516063454464

# 11b. compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_fmt_V10_R01_S10_nopol.ps &

# 12a. try polarities + components PV + PR + S BUT constrained to DC
# NOTE  this MUST be a worse solution than the non-DC version, since this solution was considered in the non-DC search
cap.pl -H0.01 -P0.5e+0.5/1/30 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -I5/0.1 -J0/0/0/0 -E1 -K1 -Y1 -Mutuhalf_4/2.4 -Zw_utuhalf_P01_V10_R01_S10.dat 20100516063454464 

# 12b. compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_DC_V10_R01_S10.ps &

# -----------------------------------------------------------
# Part 7. run cap inversions for specific physical models:  double couple, opening crack, closing crack
# Inversions are with polarities + body waves.

# 1a. Run cap for double couple (dc). NOTE I flag needs only two parameters
cap.pl -H0.01 -P1e-5/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1 -J0/0/0/0 -Mutuhalf_4/2.9 -Zw_utuhalf_P01_V10_R01_S00.dat 20100516063454464 

# 1b. Compare results
gv 20100516063454464/utuhalf_004.ps &
gv 20100516063454464_check/utuhalf_004_dc_P01_V10_R01_S00.ps

# 2a. Run cap for opening crack (oc)
# NOTE start magnitude is 2.4
cap.pl -H0.01 -P1e-4/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1/5 -J-90/90/-30/-30 -Mutuhalf_4/2.4 -Zw_utuhalf_P01_V10_R01_S00.dat 20100516063454464 

# 2b. Compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_oc_P01_V10_R01_S00.ps

# 3a. Run cap for closing crack (cc)
cap.pl -H0.01 -P2e-5/1/30 -p0.1 -S0.05/2.0/0 -T1.5/60 -D1/1/0.5 -C2/10/0.25/0.5 -F0.0 -L0.1 -W1 -E1 -K1 -Y1 -I5/0.1/5 -J-90/90/30/30 -Mutuhalf_4/2.9 -Zw_utuhalf_P01_V10_R01_S00.dat 20100516063454464 

# 3b. Compare results
gv 20100516063454464/utuhalf_004_fmt.ps &
gv 20100516063454464_check/utuhalf_004_cc_P01_V10_R01_S00.ps

# -----------------------------------------------------------
# Part 8. Uturuncu event 20100516063454464, first motion polarity

# 0. Set cap.c to its original condition
cd $CAPHOME
git checkout cap.c 

# 1. Make sure cap is compiled with the following flags, then compile
# NOTE this run should produce the file out.misfit.fmp_
#
# FTC_data=1
# FTC_green=0
# skip_zero_weights=0
# only_first_motion=1
#
# Compile cap
make all

# 3. Run cap
cd $CAPHOME/EXAMPLES
cap.pl -F0.0 -I5/0/5 -J-90/90/-30/30 -Mutuhalf_4/2.4 -E1 -K1 -Y1 -Zw_utuhalf_P01_V10_R01_S10.dat 20100516063454464

# Next compute summary of first motion polarities using the output file
python $CAPHOME/misfit2lune.py out.misfit.fmp_ out.misfit_summary

# 4. Plot polarity misfit on the lune with file out.misfit_summary
# PENDING

# NOTE
# 1. Output file from cap run (step 3) will be file: out.misfit.fmp_
# This file is 708M for grid spacing of 5 degrees and can be deleted after computing summary
# 2. No figure should be created when running first motion polarity (i.e. run cap without -P flag)

# ==============================================================================
# Part 9. Uturuncu event 20110622023324299
# This example shows filter improvement for small signals when using flag filter-then-cut during cap run.
# 1. FTC_data=0 (original) first cuts sections, then filters each section (cut-then-filter)
# 2. FTC_data=1 first filters the entire seismogram, then cuts sections (filter-then-cut)

# 0. prepare run
mkdir -p $CAPRUN/inv/utuhalf
cd $CAPRUN/inv/utuhalf/
rsync -av $CAPHOME/EXAMPLES/20110622023324299 .

# 1a. Start from default cap
cd $CAPHOME
svn revert cap.c

# 1b. cut-then-filter data. In cap.c set the flags below, compile then run
# FTC_data=0
# FTC_green=0
# skip_zero_weights=0

make cap
cd $CAPHOME/EXAMPLES
cap.pl -H0.01 -P2e-5/1/30 -S0.1/2.0/0 -T1.5/60.0 -D1/1/0.5 -C1/10/0.1/0.4 -W1 -Y1 -F0 -L0.05 -E1 -K1 -I5/0/5 -J33.748/33.748/40/40 -R215/215/69.41/69.41/40/40 -Mutuhalf_9/0.6 -Zweight.dat 20110622023324299 

# 2. compare results
gv 20110622023324299/utuhalf_009_fmt.ps &
gv $CAPHOME/EXAMPLES/20110622023324299_check/utuhalf_009_fmt_cut-filter.ps &

# 3. filter-then-cut data. In cap.c set the flags below, compile then run
# FTC_data=1
# FTC_green=0

make cap
cd $CAPHOME/EXAMPLES
cap.pl -H0.01 -P2e-5/1/30 -S0.1/2.0/0 -T1.5/60.0 -D1/1/0.5 -C1/10/0.1/0.4 -W1 -Y1 -F0 -L0.05 -E1 -K1 -I5/0/5 -J33.748/33.748/40/40 -R215/215/69.41/69.41/40/40 -Mutuhalf_9/0.6 -Zweight.dat 20110622023324299 

# 4. compare results
# gv 20110622023324299/utuhalf_009_fmt.ps &
# gv $CAPHOME/EXAMPLES/20110622023324299_check/utuhalf_009_fmt_filter-cut-data.ps &

# 5. Filter-then-cut data and greens functions. In cap.c set the flags below, compile then run 
# NOTE plotting flag is set to -P0.5e+0.5/... which normalizes seismograms in each window
# FTC_data=1
# FTC_green=1

make cap
cd $CAPHOME/EXAMPLES
cap.pl -H0.01 -P0.5e+0.5/1/30 -S0.1/2.0/0 -T1.5/60.0 -D1/1/0.5 -C1/10/0.1/0.4 -W1 -Y1 -F0 -L0.05 -E1 -K1 -I5/0/5 -J33.748/33.748/40/40 -R215/215/69.41/69.41/40/40 -Mutuhalf_9/0.6 -Zweight.dat 20110622023324299 

# 6. compare results
gv 20110622023324299/utuhalf_009_fmt.ps &
gv $CAPHOME/EXAMPLES/20110622023324299_check/utuhalf_009_fmt_filter-cut-data-greens.ps &

# ==============================================================================
