#!/bin/bash

# Make sure you are NOT running this more the once for an event directory
# otherwise you will be creating something like this: eid > V1 > V1

# Preferably run in a separate directory and then move in CAP_DATABASE

# Also see: echo_catalog_txt

for ii in 2*
do
    mv $ii V1
    mkdir $ii
    mv V1 $ii
    echo "moved $ii to version directory V1"
done