#!/bin/bash
# This script automatically updates all the examples 
# CAUTION must be payed since input command might need to be updated 
# Runs and save in the Example_check Direcotry
# MIGHT want to rename the previous Example_check directory and save it (just in case)

# > cap.pl (to know what each command flag means)

# Directory for saving the examples
ExampleDir=$CAPHOME/EXAMPLES/20080418093700_check
mkdir $ExampleDir

#==================================================================================
## EXAMPLE 1: Illinois event, double couple (DC)
# depth search range for the Illinois event
deps=(5 10 15 20 25 30)
#
for dep in ${deps[@]}
do
    #printf -v dep "%02d" $dep; echo $dep
    cap.pl -H0.2 -P1 -S2/5/0 -T35/70 -F -D1/1/0.5 -C0.05/0.3/0.02/0.1 -W1 -X10 -Mcus_$dep/5.0 -E0 -K0 -Y2 20080418093700
    # Save the files
    printf -v dep "%03d" $dep; echo $dep
    cp 20080418093700/cus_${dep}.ps $ExampleDir/cus_${dep}.ps
    cp 20080418093700/cus_${dep}.out $ExampleDir/cus_${dep}.out
    cp 20080418093700/cus_${dep}_beach.ps $ExampleDir/cus_${dep}_beach.ps
done
# perform depth test
depth_test 20080418093700 cus 
# save depth test files
cp dep_20080418093700.ps $ExampleDir/depth_dc.ps
cp junk1.out $ExampleDir/junk1_dc.out
cp junk2.out $ExampleDir/junk2_dc.out

# TO BE ADDED 
#==================================================================================
## EXAMPLE 2: Illinois event, DC with P wave polarities in weight file

#==================================================================================
## EXAMPLE 3: Illinois event, DC with P wave polarities in weight file

#==================================================================================
## EXAMPLE 4: Illinois event, FMT with Zhu line search

#==================================================================================
## EXAMPLE 5: Illinois event, FMT with fixed focal mech (strike/dip/rake/iso/clvd/mag)
cap.pl -H0.2 -P1 -S2/5/0 -T35/70 -F -D1/1/0.5 -C0.05/0.3/0.02/0.1 -W1 -X10 -Mcus_15/5.21 -E0 -K0 -Y2 -R296/296/84/84/6/6 -J0.16/0/0.04/0 -I10/0 20080418093700
cp 20080418093700/cus_015_fmt.ps $ExampleDir/cus_015_fmt_fixed_zhu.ps
cp 20080418093700/cus_015.out $ExampleDir/cus_015_fmt_fixed_zhu.out
cp 20080418093700/cus_015_beach_fmt.ps $ExampleDir/cus_015_beach_fmt_fixed_zhu.ps

#==================================================================================
## EXAMPLE 6: Illinois event, DC, full grid search (no line search)
cap.pl -H0.2 -P1 -S2/5/0 -T35/70 -F -D1/1/0.5 -C0.05/0.3/0.02/0.1 -W1 -X10 -Mcus_15/5.0 -I10/0.1 -E1 -K1 -Y2 -J0/0/0/0 20080418093700
cp 20080418093700/cus_015_fmt.ps $ExampleDir/cus_015_dc_grid.ps 
cp 20080418093700/cus_015.out $ExampleDir/cus_015_dc_grid.out
cp 20080418093700/cus_015_beach_fmt.ps $ExampleDir/cus_015_beach_dc_grid.ps 

#==================================================================================
## EXAMPLE 8: Illinois event, FMT with lune parameterization, full grid search (no line search)

cap.pl -H0.2 -P1 -S2/5/0 -T35/70 -F -D1/1/0.5 -C0.05/0.3/0.02/0.1 -W1 -X10 -Mcus_15/5.0 -I10/0.2/10 -E1 -K1 -Y2 -J-90/90/-30/30 20080418093700
cp 20080418093700/cus_015_fmt.ps $ExampleDir/cus_015_fmt_grid.ps
cp 20080418093700/cus_015.out $ExampleDir/cus_015_fmt_grid.out
cp 20080418093700/cus_015_beach_fmt.ps $ExampleDir/cus_015_beach_fmt_grid.ps

#==================================================================================
## EXAMPLE 9: Illinois event, Direct search FMT (LUNE parameterization) with fixed focal mech (strike/dip/rake/iso/clvd/mag)

cap.pl -H0.2 -P1 -S2/5/0 -T35/70 -F -D1/1/0.5 -C0.05/0.3/0.02/0.1 -W1 -X10 -Mcus_15/5.21 -E1 -K1 -Y2 -R296/296/84/84/6/6 -J-30/30/10/10 -I10/0/0 20080418093700
cp 20080418093700/cus_015_fmt.ps $ExampleDir/cus_015_fmt_fixed_lune.ps
cp 20080418093700/cus_015.out $ExampleDir/cus_015_fmt_fixed_lune.out
cp 20080418093700/cus_015_beach_fmt.ps $ExampleDir/cus_015_beach_fmt_fixed_lune.ps

#==================================================================================
## EXAMPLE 10: Illinois event, DC with random sample search (optional: grid-search over Mw)

cap.pl -H0.2 -P1 -S2/5/0 -T35/70 -F -D1/1/0.5 -C0.05/0.3/0.02/0.1 -W1 -X10 -Mcus_15/5.2 -I2/0 -E1 -K2 -Y2 -J0/0/0/0 20080418093700
cp 20080418093700/cus_015_fmt.ps $ExampleDir/cus_015_dc_rand.ps
cp 20080418093700/cus_015.out $ExampleDir/cus_015_dc_rand.out
cp 20080418093700/cus_015_beach_fmt.ps $ExampleDir/cus_015_beach_dc_rand.ps

#==================================================================================
## EXAMPLE 11: Illinois event, FMT-fixed-magnitude with random sample search (optional: grid-search over Mw)

cap.pl -H0.2 -P1 -S2/5/0 -T35/70 -F -D1/1/0.5 -C0.05/0.3/0.02/0.1 -W1 -X10 -Mcus_15/5.2 -I2/0/10 -E1 -K2 -Y2 -J0/1/0/1 20080418093700
cp 20080418093700/cus_015_fmt.ps $ExampleDir/cus_015_fmt_rand.ps
cp 20080418093700/cus_015.out $ExampleDir/cus_015_fmt_rand.out
cp 20080418093700/cus_015_beach_fmt.ps $ExampleDir/cus_015_beach_fmt_rand.ps

