function [eid] = capout2psmeca_MOOS(ddir,filename)
% INPUT
% ddir      Data directory containing CAP output files 
% filename  psmeca filename generated from combining CAP output files
%
% Vipul Silwal
% 9 Sept, 2015

ipsmeca = 0;    % for outputting in psmeca format
ilatex = 1;     % if you want to display in latex format
icatalog = 0;   % read AEC catalog
iunc = 0;       % for printing out the latex format table with the unc (will look for the uncerainty dir)
itable = 0;     % for writting the mech table
q = dir(strcat(ddir,'*out'));

% read from the CAP.out files
for ii=1:length(q)
    [otime(ii,1),elat(ii,1),elon(ii,1),edep(ii,1),strike(ii,1),dip(ii,1),rake(ii,1),M(:,ii),Mw(ii,1),...
        eid(ii,1),capmod,capdep(ii,1),rms,vr(ii),Pwin,Swin,Nstn(ii,1),Pstn,Sstn]=...
        read_capout_old(strcat(ddir,q(ii).name));
    eid
end

% get event info from the AEC catalog
axmoos = [-154 -146 58 62.5];
ax3 = [axmoos -10 200];
oran = [datenum(2007,8,15) datenum(2009,8,15)];
Mwran = [3.5 10];

if icatalog
    [otime1,lat1,lon1,dep1,M1,M0,Mw1,eid1,depc] = read_mech_AEC(oran,ax3,Mwran);
end

% get uncertainty measure info
% uncertainty directory basically contains all the eid_result.dat files
% (these are generated by CAP_unc)
if iunc
    uncdir = '/home/vipul/gmt/data/cap/MOOS/L1_M111_unc/';
    u = dir(strcat(uncdir,'*dat')); % length(u) must be equalt to length(q)
    for ii = 1:length(u)
        [unc(ii,1)] = dlmread(strcat(uncdir,u(ii).name));
    end
end

% output for Latex table
if ilatex
    for ii=1:length(q)
        evnt_id = eid{ii};
        if (and(icatalog,iunc))
            fprintf('%d & %s & %3.2f & %3.2f & %3.0f & %3.0f & %3.0f & %2.1f & %d & (%3.1f) & %2.0f & %1.2f & %d \\\\ \n',...
                ii,evnt_id,elat(ii),elon(ii),strike(ii),dip(ii),rake(ii),Mw(ii),capdep(ii),depc(ii),vr(ii),unc(ii),Nstn(ii));
        else
            fprintf('%d & %s & %3.2f & %3.2f & %3.0f & %3.0f & %3.0f & %2.1f & %d & %d \\\\ \n',...
                ii+21,evnt_id,elat(ii),elon(ii),strike(ii),dip(ii),rake(ii),Mw(ii),capdep(ii),Nstn(ii));
        end
    end
end

for ii=1:length(q)
    fprintf('%s  %3.2f  %3.2f  %3.0f  %3.0f  %3.0f  %2.1f  %d \n',...
                eid{ii},elat(ii),elon(ii),strike(ii),dip(ii),rake(ii),Mw(ii),capdep(ii));
end

% psmeca output for GMT (FIX THIS - USE DIFFERENT FILENAME)
if ipsmeca
   write_psmeca(filename,otime,elat,elon,capdep,M,eid);
end

% write mech table (for paper supplement)
if itable
    write_mech_table(strcat(filename,'_table'),otime,elat,elon,capdep,M,eid)
end

% ====================================
% EXAMPLES
if 0
    % Part I catalog
    ddir = '/home/vipul/CAP/inv/scak/MOOS/RESULTS/L1_M111_out/';
    gmtdir = '/home/vipul/gmt/data/cmt/CAP/';
    filename = strcat(gmtdir,'PartI');
    capout2psmeca_MOOS(ddir,filename)
    % Part II catalog
    ddir = '/home/vipul/CAP/inv/scak/SCAK/RESULTS/out/';
    gmtdir = '/home/vipul/gmt/data/cmt/CAP/';
    filename = strcat(gmtdir,'PartII');
    capout2psmeca_MOOS(ddir,filename)
    % Full catalog
    ddir = '/home/vipul/CAP/inv/scak/SCAK/RESULTS/out_full/';
    gmtdir = '/home/vipul/gmt/data/cmt/CAP/';
    filename = strcat(gmtdir,'SCAKcatalog');
    capout2psmeca_MOOS(ddir,filename)
    % Events from aktomo catalog
    ddir = '/home/vipul/CAP/inv/aktomo/scak/RESULTS/out/';
    gmtdir = '/home/vipul/gmt/data/cmt/CAP/';
    filename = strcat(gmtdir,'aktomoIcatalog');
    capout2psmeca_MOOS(ddir,filename)
end
