#!/bin/tcsh

rm MT_meta.txt
foreach file ( 20*out )
  head -1 $file >> MT_meta.txt
  tail -1 $file >> MT_meta.txt
  echo "$file"
end
#ls 20*out | head -1 >> MT_meta.txt
#ls 20*out | tail -1 >> MT_meta.txt
